version: "3.8"
services:
  kaspersky-feeds-for-opencti:
    build: .
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=ChangeMe
      - CONNECTOR_ID=ChangeMe
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=Kaspersky Feeds
      - CONNECTOR_SCOPE=kaspersky
      - CONNECTOR_CONFIDENCE_LEVEL=100
      - CONNECTOR_LOG_LEVEL=info
      - CONNECTOR_UPDATE_EXISTING_DATA=false
      - CONNECTOR_EXPOSE_METRICS=false
      - KASPERSKY_API_ROOT=https://taxii.tip.kaspersky.com/v2/
      - KASPERSKY_API_TOKEN=ChangeMe
      - KASPERSKY_INITIAL_HISTORY=604800 # 7 days in seconds
      - KASPERSKY_UPDATE_INTERVAL=3600 # 1 hour in seconds
    restart: always
